package com.my.digi.breeds;

import android.content.Context;
import android.content.res.AssetManager;
import java.io.InputStream;
import java.util.Arrays;

/**
 * Created by Darryl on 12/17/2016.
 */

public class Database {

    String[] dogBreedArray, dogCategoryArray, dogLifespanArray, dogImageNameArray, dogMidArray;
    int[] dogFriendlinessArray, dogPlayfulnessArray;
    Context ourContext;

    public Database(Context c) {
        this.ourContext = c;

        //Dog reference tables
        dogBreedArray = new String[]
                {
                        "Affenpinscher",
                        "Afghan Hound",
                        "African Hunting Dog",
                        "Airedale",
                        "Akita",
                        "American Bulldog",
                        "American Cocker Spaniel",
                        "American Foxhound",
                        "American Pit Bull Terrier",
                        "American Staffordshire Terrier",
                        "Appenzeller",
                        "Australian Cattle Dog",
                        "Australian Shepherd",
                        "Australian Terrier",
                        "Basenji",
                        "Basset",
                        "Beagle",
                        "Bearded Collie",
                        "Bedlington Terrier",
                        "Berger Blanc Suisse",
                        "Berger Picard",
                        "Bernese Mountain Dog",
                        "Bichon Frise",
                        "Black And Tan Coonhound",
                        "Blenheim Spaniel",
                        "Bloodhound",
                        "Bluetick",
                        "Bolognese",
                        "Border Collie",
                        "Border Terrier",
                        "Borzoi",
                        "Boston Bull",
                        "Bouvier Des Flandres",
                        "Boxer",
                        "Boykin Spaniel",
                        "Brabancon Griffon",
                        "Braque D Auvergne",
                        "Briard",
                        "Brittany Spaniel",
                        "Bull Mastiff",
                        "Cairn",
                        "Canaan Dog",
                        "Cane Corso",
                        "Cardigan",
                        "Cavalier King Charles Spaniel",
                        "Cesky Terrier",
                        "Chesapeake Bay Retriever",
                        "Chihuahua",
                        "Chow",
                        "Clumber",
                        "Cockapoo",
                        "Cocker Spaniel",
                        "Collie",
                        "Curly Coated Retriever",
                        "Czechoslovakian Wolfdog",
                        "Dachshund",
                        "Dalmation",
                        "Dandie Dinmont",
                        "Dhole",
                        "Dingo",
                        "Doberman",
                        "English Foxhound",
                        "English Setter",
                        "English Springer",
                        "Entlebucher",
                        "Eskimo Dog",
                        "Field Spaniel",
                        "Finnish Spitz",
                        "Flat Coated Retriever",
                        "French Bulldog",
                        "German Shepherd",
                        "German Short Haired Pointer",
                        "German Spitz",
                        "Giant Schnauzer",
                        "Golden Retriever",
                        "Goldendoodle",
                        "Gordon Setter",
                        "Great Dane",
                        "Great Pyrenees",
                        "Greater Swiss Mountain Dog",
                        "Greyhound",
                        "Groenendael",
                        "Havanese",
                        "Ibizan Hound",
                        "Irish Setter",
                        "Irish Terrier",
                        "Irish Water Spaniel",
                        "Irish Wolfhound",
                        "Italian Greyhound",
                        "Jack Russell Terrier",
                        "Japanese Spaniel",
                        "Keeshond",
                        "Kelpie",
                        "Kerry Blue Terrier",
                        "Komondor",
                        "Kooikerhondje",
                        "Kuvasz",
                        "Labrador Retriever",
                        "Lakeland Terrier",
                        "Leonberg",
                        "Lhasa",
                        "Lowchen",
                        "Malamute",
                        "Malinois",
                        "Maltese Dog",
                        "Mexican Hairless",
                        "Miniature Pinscher",
                        "Miniature Poodle",
                        "Miniature Schnauzer",
                        "Newfoundland",
                        "Norfolk Terrier",
                        "Norwegian Buhund",
                        "Norwegian Elkhound",
                        "Norwegian Lundehund",
                        "Norwich Terrier",
                        "Old English Bulldog",
                        "Old English Sheepdog",
                        "Otterhound",
                        "Papillon",
                        "Pekinese",
                        "Pembroke",
                        "Pharaoh Hound",
                        "Polish Lowland Sheepdog",
                        "Pomeranian",
                        "Pug",
                        "Puli",
                        "Pumi",
                        "Redbone",
                        "Rhodesian Ridgeback",
                        "Rottweiler",
                        "Saarloos Wolfdog",
                        "Saint Bernard",
                        "Saluki",
                        "Samoyed",
                        "Schipperke",
                        "Schnoodle",
                        "Scotch Terrier",
                        "Scottish Deerhound",
                        "Sealyham Terrier",
                        "Shar Pei",
                        "Shetland Sheepdog",
                        "Shiba Inu",
                        "Shih Tzu",
                        "Siberian Husky",
                        "Silky Terrier",
                        "Sloughi",
                        "Slovak Cuvac",
                        "Soft Coated Wheaten Terrier",
                        "Staffordshire Bullterrier",
                        "Standard Poodle",
                        "Standard Schnauzer",
                        "Sussex Spaniel",
                        "Tervuren",
                        "Tibetan Mastiff",
                        "Tibetan Terrier",
                        "Toy Poodle",
                        "Toy Terrier",
                        "Vizsla",
                        "Walker Hound",
                        "Weimaraner",
                        "Welsh Springer Spaniel",
                        "West Highland White Terrier",
                        "Whippet",
                        "White Shepherd",
                        "Wire Haired Fox Terrier",
                        "Yorkshire Terrier"
                };

        dogMidArray = new String[]

                {
                        "/m/01p2dp",
                        "/m/011l1",
                        "/m/02twvh",
                        "/m/017t3p",
                        "/m/0cqg0t",
                        "/m/02z_05",
                        "/m/01p2lr",
                        "/m/06v_sc",
                        "/m/049jr6",
                        "/m/04m4bq",
                        "/m/08mb92",
                        "/m/029bcs",
                        "/m/02kf24",
                        "/m/02gf0p",
                        "/m/01j0x",
                        "/m/0hw_s",
                        "/m/01dj7",
                        "/m/02nscg",
                        "/m/02wbf7",
                        "/m/03gqk9t",
                        "/m/0c779w",
                        "/m/01p5rd",
                        "/m/0nr94",
                        "/m/01d7mc",
                        "/m/04nmst",
                        "/m/018z4d",
                        "/m/020dr1",
                        "/m/025swlx",
                        "/m/0pwdp",
                        "/m/0353h4",
                        "/m/01j0g",
                        "/m/02x9dk",
                        "/m/03h71r",
                        "/m/01llgk",
                        "/m/08s0ws",
                        "/m/04xx17",
                        "/m/02r4blp",
                        "/m/02_70q",
                        "/m/03b8_5",
                        "/m/01hxnh",
                        "/m/02z57c",
                        "/m/06g210",
                        "/m/04fzvx",
                        "/m/02kgrx",
                        "/m/01xtxb",
                        "/m/03jgg9",
                        "/m/01cx_v",
                        "/m/0khhs",
                        "/m/0c40t",
                        "/m/01pm38",
                        "/m/02fxgn",
                        "/m/02wbgd",
                        "/m/02kcj6",
                        "/m/07bln6",
                        "/m/0b3s8y",
                        "/m/02cj3",
                        "/m/02rjc05",
                        "/m/0353qr",
                        "/m/02dcv",
                        "/m/0gz1v",
                        "/m/06pq2r",
                        "/m/06w066",
                        "/m/0gz1d",
                        "/m/020z5t",
                        "/m/02kn5w",
                        "/m/017lw7",
                        "/m/03ht9m",
                        "/m/035405",
                        "/m/01p8tm",
                        "/m/038wt3",
                        "/m/0km5c",
                        "/m/02kw9d",
                        "/m/02q64g_",
                        "/m/04q65n",
                        "/m/01t032",
                        "/m/02fvym",
                        "/m/0gz0j",
                        "/m/0lbw4",
                        "/m/01hzb8",
                        "/m/037jtq",
                        "/m/03d12",
                        "/m/02vjrc",
                        "/m/03ydd_",
                        "/m/03ys4",
                        "/m/039rzl",
                        "/m/032xlb",
                        "/m/044lwh",
                        "/m/03ysk",
                        "/m/03ysz",
                        "/m/01d7fl",
                        "/m/045tty",
                        "/m/04dmm",
                        "/m/0gz2b",
                        "/m/03cq_p",
                        "/m/04dm6",
                        "/m/0hkfc",
                        "/m/0j7vm",
                        "/m/0km3f",
                        "/m/032xv1",
                        "/m/06rq64",
                        "/m/03vrbz",
                        "/m/05sfy0",
                        "/m/01p3d7",
                        "/m/02vjtz",
                        "/m/02cyl6",
                        "/m/01k9j2",
                        "/m/03svl1",
                        "/m/0xn59p7",
                        "/m/020z66",
                        "/m/01z404",
                        "/m/05d1_4",
                        "/m/0632tn",
                        "/m/03vgc4",
                        "/m/01z0mh",
                        "/m/03jjm4",
                        "/m/0622q7",
                        "/m/03j7p3",
                        "/m/05717m",
                        "/m/01pkw7",
                        "/m/02bp0t",
                        "/m/02kh2h",
                        "/m/0gvx7",
                        "/m/05qgc4",
                        "/m/016wfy",
                        "/m/016wkx",
                        "/m/02kvr1",
                        "/m/07vgwn",
                        "/m/0778jb",
                        "/m/018g_l",
                        "/m/01nw62",
                        "/m/028y5g",
                        "/m/02p1d4",
                        "/m/076zg",
                        "/m/017lg8",
                        "/m/01dv7j",
                        "/m/0b26w3",
                        "/m/018ywq",
                        "/m/076_8",
                        "/m/032xq9",
                        "/m/03fyyd",
                        "/m/0182yx",
                        "/m/077hh",
                        "/m/01s7fj",
                        "/m/071jj",
                        "/m/05h0pv",
                        "/m/076_n",
                        "/m/03mgvkn",
                        "/m/02rfz5",
                        "/m/01kv93",
                        "/m/0xn56pv",
                        "/m/04p3f7",
                        "/m/0d5yby",
                        "/m/02vjwg",
                        "/m/03w0j9",
                        "/m/05pyhd",
                        "/m/02kfwr",
                        "/m/0353wm",
                        "/m/0183xd",
                        "/m/0773fb",
                        "/m/02kwjt",
                        "/m/081zj5",
                        "/m/02f1fz",
                        "/m/08626",
                        "/m/05912f",
                        "/m/03_vn4",
                        "/m/01_gx_"
                };

        dogCategoryArray = new String[]

                {
                        "Toy",
                        "Hound",
                        "Wild Dog",
                        "Terrier",
                        "Working",
                        "Non-Sporting",
                        "Sporting",
                        "Hound",
                        "Terrier",
                        "Terrier",
                        "Working",
                        "Herding",
                        "Herding",
                        "Terrier",
                        "Hound",
                        "Hound",
                        "Hound",
                        "Herding",
                        "Terrier",
                        "Herding",
                        "Herding",
                        "Working",
                        "Non-Sporting",
                        "Hound",
                        "Toy",
                        "Hound",
                        "Hound",
                        "Toy",
                        "Herding",
                        "Terrier",
                        "Hound",
                        "Non-Sporting",
                        "Herding",
                        "Working",
                        "Sporting",
                        "Toy",
                        "Sporting",
                        "Herding",
                        "Sporting",
                        "Working",
                        "Terrier",
                        "Herding",
                        "Working",
                        "Herding",
                        "Toy",
                        "Terrier",
                        "Sporting",
                        "Toy",
                        "Non-Sporting",
                        "Sporting",
                        "Toy",
                        "Sporting",
                        "Herding",
                        "Sporting",
                        "Hound",
                        "Hound",
                        "Working",
                        "Terrier",
                        "Wild Dog",
                        "Wild Dog",
                        "Working",
                        "Hound",
                        "Sporting",
                        "Sporting",
                        "Herding",
                        "Non-Sporting",
                        "Sporting",
                        "Non-Sporting",
                        "Sporting",
                        "Non-Sporting",
                        "Herding",
                        "Sporting",
                        "Non-Sporting",
                        "Working",
                        "Sporting",
                        "Toy",
                        "Sporting",
                        "Working",
                        "Working",
                        "Working",
                        "Hound",
                        "Herding",
                        "Toy",
                        "Hound",
                        "Sporting",
                        "Terrier",
                        "Sporting",
                        "Hound",
                        "Toy",
                        "Terrier",
                        "Toy",
                        "Non-Sporting",
                        "Herding",
                        "Terrier",
                        "Working",
                        "Sporting",
                        "Working",
                        "Sporting",
                        "Terrier",
                        "Working",
                        "Non-Sporting",
                        "Non-Sporting",
                        "Working",
                        "Herding",
                        "Toy",
                        "Non-Sporting",
                        "Toy",
                        "Toy",
                        "Terrier",
                        "Working",
                        "Terrier",
                        "Herding",
                        "Hound",
                        "Non-Sporting",
                        "Terrier",
                        "Non-Sporting",
                        "Herding",
                        "Hound",
                        "Toy",
                        "Toy",
                        "Herding",
                        "Hound",
                        "Herding",
                        "Toy",
                        "Toy",
                        "Herding",
                        "Herding",
                        "Hound",
                        "Hound",
                        "Working",
                        "Hound",
                        "Working",
                        "Hound",
                        "Working",
                        "Non-Sporting",
                        "Toy",
                        "Terrier",
                        "Hound",
                        "Terrier",
                        "Non-Sporting",
                        "Herding",
                        "Non-Sporting",
                        "Toy",
                        "Working",
                        "Toy",
                        "Hound",
                        "Working",
                        "Terrier",
                        "Terrier",
                        "Non-Sporting",
                        "Working",
                        "Sporting",
                        "Herding",
                        "Working",
                        "Non-Sporting",
                        "Toy",
                        "Toy",
                        "Sporting",
                        "Hound",
                        "Sporting",
                        "Sporting",
                        "Terrier",
                        "Hound",
                        "Herding",
                        "Terrier",
                        "Toy"
                };

        dogLifespanArray = new String[]

                {
                        "10-12yrs",
                        "10-13yrs",
                        "10-12yrs",
                        "10-13yrs",
                        "10-14yrs",
                        "8-10yrs",
                        "12-15yrs",
                        "8-15yrs",
                        "10-15yrs",
                        "12-15yrs",
                        "13-17yrs",
                        "12-14yrs",
                        "12-16yrs",
                        "15yrs",
                        "10-12yrs",
                        "12-15yrs",
                        "13-16yrs",
                        "12-14yrs",
                        "14-16yrs",
                        "10-13yrs",
                        "12-15yrs",
                        "7-10yrs",
                        "15yrs",
                        "10-12yrs",
                        "10-14yrs",
                        "8-10yrs",
                        "12-14yrs",
                        "13-15yrs",
                        "12-16yrs",
                        "12-14yrs",
                        "10-13yrs",
                        "11-13yrs",
                        "10-15yrs",
                        "8-10yrs",
                        "10-14yrs",
                        "12-15yrs",
                        "12-15yrs",
                        "10-12yrs",
                        "12-14yrs",
                        "8-12yrs",
                        "14-15yrs",
                        "12-14yrs",
                        "10-11yrs",
                        "12-14yrs",
                        "10-14yrs",
                        "10-15yrs",
                        "10-13yrs",
                        "12-20yrs",
                        "12-15yrs",
                        "10-12yrs",
                        "14-18yrs",
                        "12-15yrs",
                        "10-14yrs",
                        "10-15yrs",
                        "12-16yrs",
                        "12-15yrs",
                        "10-13yrs",
                        "12-14yrs",
                        "10-16yrs",
                        "10-14yrs",
                        "10yrs",
                        "10-13yrs",
                        "10-12yrs",
                        "12-14yrs",
                        "10-13yrs",
                        "12-15yrs",
                        "11-15yrs",
                        "12-15yrs",
                        "10-13yrs",
                        "9-11yrs",
                        "10-13yrs",
                        "12-14yrs",
                        "12-15yrs",
                        "10-12yrs",
                        "10-12yrs",
                        "10-15yrs",
                        "10-12yrs",
                        "7-10yrs",
                        "10-12yrs",
                        "7-9yrs",
                        "10-13yrs",
                        "12-14yrs",
                        "14-15yrs",
                        "11-14yrs",
                        "10-11yrs",
                        "12-16yrs",
                        "12-15yrs",
                        "6-8yrs",
                        "12-15yrs",
                        "12-14yrs",
                        "12-14yrs",
                        "12-15yrs",
                        "10-13yrs",
                        "12-15yrs",
                        "10-12yrs",
                        "12-15yrs",
                        "8-10yrs",
                        "10-13yrs",
                        "12-15yrs",
                        "6-8yrs",
                        "12-15yrs",
                        "12-15yrs",
                        "12-15yrs",
                        "12-14yrs",
                        "15-18yrs",
                        "12-14yrs",
                        "15yrs",
                        "14-18yrs",
                        "12-14yrs",
                        "8-10yrs",
                        "12-15yrs",
                        "12-15yrs",
                        "10-12yrs",
                        "6-8yrs",
                        "12-15yrs",
                        "8-10yrs",
                        "10-12yrs",
                        "10-15yrs",
                        "13-17yrs",
                        "14-18yrs",
                        "12-14yrs",
                        "12-14yrs",
                        "10-12yrs",
                        "15-18yrs",
                        "12-14yrs",
                        "12-16yrs",
                        "13-15yrs",
                        "10-12yrs",
                        "10-12yrs",
                        "8-10yrs",
                        "10-12yrs",
                        "7-10yrs",
                        "12-14yrs",
                        "12-14yrs",
                        "13-15yrs",
                        "13-17yrs",
                        "11-13yrs",
                        "8-10yrs",
                        "14-17yrs",
                        "10yrs",
                        "12-14yrs",
                        "12-16yrs",
                        "10-18yrs",
                        "12yrs",
                        "12-15yrs",
                        "12-15yrs",
                        "8-10yrs",
                        "12-15yrs",
                        "12-14yrs",
                        "14-18yrs",
                        "13-15yrs",
                        "10-15yrs",
                        "10-12yrs",
                        "10-14yrs",
                        "12-15yrs",
                        "14-18yrs",
                        "12-15yrs",
                        "10-14yrs",
                        "10-13yrs",
                        "12-15yrs",
                        "12-15yrs",
                        "15-20yrs",
                        "12-15yrs",
                        "10-13yrs",
                        "12-14yrs",
                        "12-16yrs"
                };

        dogImageNameArray = new String[]

                {
                        "affenpinscher",
                        "afghan_hound",
                        "african_hunting_dog",
                        "airedale",
                        "akita",
                        "american_bulldog",
                        "american_cocker_spaniel",
                        "american_foxhound",
                        "american_pit_bull_terrier",
                        "american_staffordshire_terrier",
                        "appenzeller",
                        "australian_cattle_dog",
                        "australian_shepherd",
                        "australian_terrier",
                        "basenji",
                        "basset",
                        "beagle",
                        "bearded_collie",
                        "bedlington_terrier",
                        "berger_blanc_suisse",
                        "berger_picard",
                        "bernese_mountain_dog",
                        "bichon_frise",
                        "black_and_tan_coonhound",
                        "blenheim_spaniel",
                        "bloodhound",
                        "bluetick",
                        "bolognese",
                        "border_collie",
                        "border_terrier",
                        "borzoi",
                        "boston_bull",
                        "bouvier_des_flandres",
                        "boxer",
                        "boykin_spaniel",
                        "brabancon_griffon",
                        "braque_d_auvergne",
                        "briard",
                        "brittany_spaniel",
                        "bull_mastiff",
                        "cairn",
                        "canaan_dog",
                        "cane_corso",
                        "cardigan",
                        "cavalier_king_charles_spaniel",
                        "cesky_terrier",
                        "chesapeake_bay_retriever",
                        "chihuahua",
                        "chow",
                        "clumber",
                        "cockapoo",
                        "cocker_spaniel",
                        "collie",
                        "curly_coated_retriever",
                        "czechoslovakian_wolfdog",
                        "dachshund",
                        "dalmation",
                        "dandie_dinmont",
                        "dhole",
                        "dingo",
                        "doberman",
                        "english_foxhound",
                        "english_setter",
                        "english_springer",
                        "entlebucher",
                        "eskimo_dog",
                        "field_spaniel",
                        "finnish_spitz",
                        "flat_coated_retriever",
                        "french_bulldog",
                        "german_shepherd",
                        "german_short_haired_pointer",
                        "german_spitz",
                        "giant_schnauzer",
                        "golden_retriever",
                        "goldendoodle",
                        "gordon_setter",
                        "great_dane",
                        "great_pyrenees",
                        "greater_swiss_mountain_dog",
                        "greyhound",
                        "groenendael",
                        "havanese",
                        "ibizan_hound",
                        "irish_setter",
                        "irish_terrier",
                        "irish_water_spaniel",
                        "irish_wolfhound",
                        "italian_greyhound",
                        "jack_russell_terrier",
                        "japanese_spaniel",
                        "keeshond",
                        "kelpie",
                        "kerry_blue_terrier",
                        "komondor",
                        "kooikerhondje",
                        "kuvasz",
                        "labrador_retriever",
                        "lakeland_terrier",
                        "leonberg",
                        "lhasa",
                        "lowchen",
                        "malamute",
                        "malinois",
                        "maltese_dog",
                        "mexican_hairless",
                        "miniature_pinscher",
                        "miniature_poodle",
                        "miniature_schnauzer",
                        "newfoundland",
                        "norfolk_terrier",
                        "norwegian_buhund",
                        "norwegian_elkhound",
                        "norwegian_lundehund",
                        "norwich_terrier",
                        "old_english_bulldog",
                        "old_english_sheepdog",
                        "otterhound",
                        "papillon",
                        "pekinese",
                        "pembroke",
                        "pharaoh_hound",
                        "polish_lowland_sheepdog",
                        "pomeranian",
                        "pug",
                        "puli",
                        "pumi",
                        "redbone",
                        "rhodesian_ridgeback",
                        "rottweiler",
                        "saarloos_wolfdog",
                        "saint_bernard",
                        "saluki",
                        "samoyed",
                        "schipperke",
                        "schnoodle",
                        "scotch_terrier",
                        "scottish_deerhound",
                        "sealyham_terrier",
                        "shar_pei",
                        "shetland_sheepdog",
                        "shiba_inu",
                        "shih_tzu",
                        "siberian_husky",
                        "silky_terrier",
                        "sloughi",
                        "slovak_cuvac",
                        "soft_coated_wheaten_terrier",
                        "staffordshire_bullterrier",
                        "standard_poodle",
                        "standard_schnauzer",
                        "sussex_spaniel",
                        "tervuren",
                        "tibetan_mastiff",
                        "tibetan_terrier",
                        "toy_poodle",
                        "toy_terrier",
                        "vizsla",
                        "walker_hound",
                        "weimaraner",
                        "welsh_springer_spaniel",
                        "west_highland_white_terrier",
                        "whippet",
                        "white_shepherd",
                        "wire_haired_fox_terrier",
                        "yorkshire_terrier"
                };

        dogFriendlinessArray = new int[]

                {
                        1,
                        3,
                        1,
                        4,
                        3,
                        5,
                        5,
                        5,
                        4,
                        4,
                        3,
                        5,
                        5,
                        4,
                        2,
                        5,
                        5,
                        4,
                        4,
                        5,
                        5,
                        3,
                        3,
                        5,
                        3,
                        5,
                        4,
                        3,
                        5,
                        5,
                        2,
                        5,
                        5,
                        3,
                        3,
                        1,
                        5,
                        4,
                        5,
                        3,
                        4,
                        5,
                        4,
                        5,
                        3,
                        3,
                        3,
                        1,
                        2,
                        3,
                        4,
                        5,
                        5,
                        4,
                        3,
                        2,
                        4,
                        4,
                        1,
                        1,
                        4,
                        5,
                        5,
                        3,
                        4,
                        2,
                        5,
                        4,
                        4,
                        2,
                        5,
                        4,
                        3,
                        3,
                        5,
                        5,
                        5,
                        3,
                        4,
                        4,
                        5,
                        4,
                        5,
                        3,
                        5,
                        4,
                        5,
                        4,
                        1,
                        3,
                        2,
                        4,
                        3,
                        4,
                        3,
                        4,
                        3,
                        5,
                        4,
                        5,
                        5,
                        3,
                        4,
                        3,
                        1,
                        3,
                        3,
                        2,
                        3,
                        5,
                        4,
                        5,
                        5,
                        3,
                        4,
                        5,
                        5,
                        4,
                        1,
                        1,
                        5,
                        4,
                        4,
                        1,
                        4,
                        4,
                        4,
                        5,
                        5,
                        2,
                        3,
                        5,
                        3,
                        5,
                        4,
                        4,
                        3,
                        5,
                        4,
                        1,
                        4,
                        3,
                        2,
                        5,
                        2,
                        2,
                        3,
                        4,
                        3,
                        5,
                        4,
                        5,
                        3,
                        3,
                        4,
                        2,
                        3,
                        3,
                        4,
                        5,
                        5,
                        4,
                        3,
                        5,
                        5,
                        1
                };

        dogPlayfulnessArray = new int[]

                {
                        4,
                        3,
                        1,
                        5,
                        3,
                        1,
                        4,
                        5,
                        4,
                        4,
                        4,
                        5,
                        5,
                        4,
                        3,
                        3,
                        5,
                        5,
                        3,
                        3,
                        5,
                        3,
                        3,
                        3,
                        3,
                        5,
                        3,
                        3,
                        5,
                        3,
                        3,
                        3,
                        3,
                        4,
                        3,
                        3,
                        4,
                        3,
                        5,
                        2,
                        4,
                        3,
                        3,
                        4,
                        3,
                        3,
                        4,
                        3,
                        2,
                        3,
                        3,
                        4,
                        3,
                        3,
                        2,
                        3,
                        5,
                        3,
                        1,
                        1,
                        3,
                        3,
                        4,
                        5,
                        4,
                        4,
                        5,
                        4,
                        5,
                        2,
                        3,
                        5,
                        4,
                        5,
                        5,
                        4,
                        5,
                        2,
                        2,
                        3,
                        3,
                        5,
                        4,
                        3,
                        5,
                        4,
                        4,
                        3,
                        3,
                        5,
                        3,
                        3,
                        4,
                        4,
                        3,
                        5,
                        3,
                        5,
                        4,
                        4,
                        3,
                        3,
                        4,
                        5,
                        3,
                        3,
                        5,
                        3,
                        3,
                        3,
                        4,
                        5,
                        3,
                        4,
                        4,
                        1,
                        3,
                        5,
                        5,
                        1,
                        4,
                        3,
                        4,
                        3,
                        3,
                        4,
                        5,
                        4,
                        4,
                        3,
                        2,
                        2,
                        3,
                        3,
                        5,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        2,
                        4,
                        4,
                        3,
                        3,
                        4,
                        3,
                        4,
                        5,
                        3,
                        5,
                        3,
                        4,
                        3,
                        5,
                        5,
                        4,
                        5,
                        4,
                        5,
                        3,
                        3,
                        5,
                        3
                };
    }

    public boolean foundBreed (String mid){
        if (Arrays.asList(dogMidArray).contains(mid))
            return true;
        else
            return false;
    }

    public int getLength (){
        return dogBreedArray.length;
    }

    public int getIndex (String mid){
        return Arrays.asList(dogMidArray).indexOf(mid);
    }

    public String getBreed (int index){
        return dogBreedArray[index];
    }

    public String getCategory (int index){
        return dogCategoryArray[index];
    }

    public String getImageName (int index){
        return dogImageNameArray[index];
    }

    public String getLifeSpan (int index){
        return dogLifespanArray[index];
    }

    public int getFriendliness (int index){
        return dogFriendlinessArray[index];
    }

    public int getPlayfulness (int index){
        return dogPlayfulnessArray[index];
    }
}